server.port=8080
spring.application.name=api-gateway
jwt.secret=e890^t@3aT%-;lQ8!ef@h3k,m45*>r9M[j0ID0{QM.$


spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**,/users/**

spring.cloud.gateway.server.webflux.routes[1].id=course-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/courses/**

spring.cloud.gateway.server.webflux.routes[2].id=enrollment-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/enrollments/**
